version: '3.1'

volumes:
  app-data:

services:

  geoip:
    image: k3nny0r/geoip
    container_name: geoip
    env_file:
      - ./geoip/geoip.env
    ports:
      - 127.0.0.1:22223:22223
    restart: always


  countit:
    image: k3nny0r/countit
    ports:
      - 127.0.0.1:5050:5050
    env_file:
      - ./countit/countit.env
    volumes:
      - app-data:/app/data_metrics
    restart: unless-stopped

  sshtarpit:
    build: .
    image: k3nny0r/sshtarpit
    env_file:
      - ./geoip/geoip.env
      - ./countit/countit.env
    ports:
      - 0.0.0.0:22222:22222
      - 127.0.0.1:22224:22224
    depends_on:
      - countit
    restart: unless-stopped
