version: '3.1'

services:

  countit:
    image: k3nny0r/countit
    ports:
      - 127.0.0.1:5050:5000
    env_file:
      - ./countit/countit.env
    volumes:
      - ./data:/app/data_metrics
    restart: unless-stopped

  sshtarpit:
    build: .
    image: k3nny0r/sshtarpit
    env_file:
      - ./geoip/geoip.env
      - ./countit/countit.env
    ports:
      - 0.0.0.0:22222:22222
      - 127.0.0.1:22224:22224
    restart: unless-stopped
